# Site settings
title: Freeman Lou's Personal Page
description: A page where I show my 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Freeman Lou
user_description: Hi! I'm a junior at Stony Brook University majoring in Computer Science. I started programming during high school, and after attending several hackathons, I decided that I would pursue CS in college. Currently I'm studying operating systems, databases, and computer vision, and I would like to pursue research in computer vision for my honors thesis. I'm always trying to learn new things and improve myself. When I'm not coding I like to exercise or go on roadtrips. My favorite book would have to be "Cryptonomicon" by Neal Stephenson, but I also enjoy reading about finance. After graduating I would like to work in industry and maybe go to grad school.
user_title: Student & Software Developer
email: freeman.lou(AT)stonybrook.edu
twitter_username: freemanlou
github_username:  freemanlou
gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
